routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//// BUILD API
Route::get('/api/{path}', function(){
   return view('layouts/app');
})->where('path','.*');



Route::group(['namespace' => 'Auth'], function () {
    Route::get('logout', 'LogoutController@logout')->name('auth.logout');
    Route::get('active/{token}', 'ActiveUserController@active')->name('auth.active');
    
    Route::get('auth/facebook', 'FacebookController@redirectToFacebook');
    Route::get('auth/facebook/callback', 'FacebookController@handleFacebookCallback');
});
Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::middleware(['auth', 'admin'])->group(function () {
            Route::name('admin.')->group(function () {
                Route::get('/', 'AdminController@index')->name('index');
                Route::prefix('users')->group(function () {
                    Route::name('users.')->group(function () {
                        Route::get('/', 'UserController@index')->name('index');
                        Route::get('/create', 'UserController@create')->name('create');
                        Route::post('/create', 'UserController@store')->name('store');
                        Route::get('/edit/{id}', 'UserController@edit')->name('edit');
                        Route::put('/edit/{id}', 'UserController@update')->name('update');
                        Route::get('/edit-password/{id}', 'UserController@editPassword')->name('edit.password');
                        Route::put('/edit-password/{id}', 'UserController@updatePassword')->name('update.password');
                        Route::delete('/delete/{id}', 'UserController@delete')->name('delete');
                    });
                    Route::prefix('{user_id}')->group(function () {
                        Route::prefix('categories')->group(function () {
                            Route::name('categories.')->group(function () {
                                Route::get('/', 'CategoryController@index')->name('index');
                                Route::get('/create', 'CategoryController@create')->name('create');
                                Route::post('/create', 'CategoryController@store')->name('store');
                                Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
                                Route::put('/edit/{id}', 'CategoryController@update')->name('update');
                                Route::delete('/delete/{id}', 'CategoryController@delete')->name('delete');
                            });
                        });
                    });
                    Route::prefix('categories/{category_id}')->group(function () {
                        Route::prefix('spends')->group(function (){
                            Route::name('spends.')->group(function (){
                                Route::get('/','SpendController@index')->name('index');
                                Route::get('create','SpendController@create')->name('create');
                                Route::post('create/{user_id}','SpendController@store')->name('store');
                                Route::get('edit/{id}','SpendController@edit')->name('edit');
                                Route::put('edit/{id}','SpendController@update')->name('update');
                                Route::delete('/delete/{id}', 'SpendController@delete')->name('delete');
                                Route::get('statistic-type','SpendController@statisticType')->name('statistic.type');
                            });
                        });
                    });
                });
                Route::prefix('users/{user_id}')->group(function (){
                    Route::prefix('spends')->group(function (){
                        Route::name('spends.')->group(function (){
                            Route::get('/','SpendController@statistic')->name('statistic');
                            Route::match(['get', 'post'],'filter','SpendController@filterStatistic')->name('filter');
                        });
                    });
                });

            });
        });
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/SpendController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\EditSpendRequest;
use App\Model\Spend;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use App\Repository\CategoryRepository;
use App\Http\Requests\Admin\AddSpendRequest;
use App\Http\Requests\Admin\EditCategoryRequest;
use App\Repository\UserRepository;
use App\Repository\SpendRepository;
use Mockery\CountValidator\Exception;

class SpendController extends Controller
{
    protected $categoryRepository;
    protected $spendRepository;
    protected $userRepository;

    public function __construct()
    {
        $this->categoryRepository = app(CategoryRepository::class);
        $this->spendRepository    = app(SpendRepository::class);
        $this->userRepository     = app(UserRepository::class);
    }

    public function index($category_id)
    {
        try {
            $spends = $this->spendRepository->getSpendFromCat($category_id);
            $category = $this->categoryRepository->detail($category_id);
            return view('admin.spends.index', ['spends' => $spends, 'category' => $category]);
        }
        catch (\Exception $e){
            Log::error('=========ERROR===SHOW==============SPEND',$e->getMessage());
            return abort(500);
         }
    }
    public function create($category_id)
    {
        try{
            $category = $this->categoryRepository->detail($category_id);
            return view('admin.spends.create',['category' => $category]);
        }catch (\Exception $e){
            Log::error('=========ERROR===CREATE==SPEND',$e->getMessage());
            return abort(500);
        }

    }
    public function store(AddSpendRequest $request,$cateogy_id,$user_id)
    {
        try{
            $arrParam = $request->all();
            $arrParam['user_id'] =  $user_id;
            $this->spendRepository->create($arrParam);
            return redirect()->route('admin.spends.index',['category_id' => $cateogy_id])->with('alert-success', trans('messages.success_created'));
        }catch (\Exception $e){
            Log::error('========ERRORS===STOGE===SPEND',$e->getMessage());
            return abort(500);
        }

    }
    public function edit($category_id,$spend_id)
    {
        try{
            $spend = $this->spendRepository->detail($spend_id,['categories']);
            if(empty($spend)) return abort(404);
            return view('admin.spends.edit',['category_id'=> $category_id,'spend' => $spend]);
        }catch (\Exception $e){
            Log::error('====EDIT_SPEND===',$e->getMessage());
            return abort(500);
        }
    }
    public function update($category_id,$spend_id, EditSpendRequest $request)
    {
        try{
             $spend = $this->spendRepository->detail($spend_id,['categories']);
             $arrParam = $request->all();
             $arrParam['user_id']     = $spend->user_id;
             $arrParam['category_id'] = $spend->category_id;
             $this->spendRepository->update($spend_id,$arrParam);
             return redirect()->route('admin.spends.index',['category_id' => $category_id])->with('alert-success', trans('messages.success_updated'));
        }catch (\Exception $e){
            Log::error('=======ERROR-UPDATE--SPEND=====',$e->getMessage());
            return abort(500);
        }
    }
    public function delete($category_id,$spend_id)
    {
        try{
            $this->spendRepository->delete($spend_id);
            return redirect()->route('admin.spends.index',['category_id' => $category_id])->with('alert-success', trans('messages.success_deleted'));
        }catch (\Exception $e){
            Log::error('=====DELETE_SPEND=========',$e->getMessage());
            return abort(500);
        }
    }
    public function statistic($user_id)
    {
        try{
            $this->checkUser($user_id);
            $categories = $this->categoryRepository->getCategoryFromUser($user_id);
            $spends     = $this->spendRepository->getSpendFromUser($user_id);
            return view('admin.spends.statistic',['categories' => $categories,'spends' => $spends,'user_id' => $user_id]);
        }catch (\Exception $e){
            Log::error('===========SPEND_STATISTIC===========',$e->getMessage());
            return abort(500);
        }
    }
    public function statisticType(Request $request,$category_id)
    {
        if(isset($request->type)){
             $type = $request->type;
             if ($type == Spend::RECEIVE || $type == Spend::BUY){
               $spends = $this->spendRepository->getTypeStatistic($category_id,$type);
                 return view('admin.spends.statistic-type',['spends' => $spends,'category_id'=>$category_id]);
             }else{
                 return abort(500);
             }
        }

    }
    public function filterStatistic(Request $request,$user_id)
    {
        $this->checkUser($user_id);
        /*
         * PARAMER FILTER
         * */
        $filter    = $request->filter;
        $from_date = $request->from_date;
        $to_date   = $request->to_date;
        $value_category = $request->filter_category;
        /*
         * / PARAMMER FILTER
         * */
        $categories = $this->categoryRepository->getCategoryFromUser($user_id);
        $spends     = $this->spendRepository->filterSpendFromUserAndDate($user_id,$filter,array('from_date' => $from_date,'to_date'=> $to_date,'vl_category' => $value_category));
        return view('admin.spends.statistic',['categories' => $categories,'spends' => $spends,'user_id' => $user_id]);
    }
    private function checkUser($user_id)
    {
        $user = $this->userRepository->detail($user_id);
        if(empty($user_id)) return abort(404);
        return $user;
    }
   
}

app/Http/Controllers/Api/SpendController.php
<?php

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;
use App\Repository\SpendRepository;
use App\Repository\CategoryRepository;
use Mockery\CountValidator\Exception;
use App\Http\Requests\User\AddSpendRequest;
use App\Http\Requests\User\EditSpendRequest;
use Illuminate\Support\Facades\Auth;

class SpendController extends Controller
{
  protected $spendRepository;
  protected $categoryRepository;
  public function __construct()
  {
    $this->spendRepository    = app(SpendRepository::class);
    $this->categoryRepository = app(CategoryRepository::class);
  }
  public function index()
  {
    // checkUser;
    
    try {
      return $this->spendRepository->querySpend(1); // Auth::id()
     } catch (Exception $e) {
         return response()->json(['error' => $e->getMessage()], 500);
     }
  }  
  public function edit($id)
  {
    try {
      $spend =  $this->spendRepository->detail($id);
      $categories = $this->categoryRepository->getCategoryFromUser(1);
      return response()->json(['spend' => $spend, 'categories' => $categories]);
  } catch (Exception $e) {
    return response()->json(['error' => $e->getMessage()], 500);
   }
  }
  public function update(EditSpendRequest $request, $id)
    {
       try{
         $arrParam                =  $request->all();
         $arrParam['user_id']     = 1; // auth()->user()->id
         $arrParam['category_id'] = $request->category;

         $spend = $this->spendRepository->update($id,$arrParam);

         return response()->json(['success' => true]);
       }catch(Exception $e){
         return response()->json(['error' => $e->getMessage()], 500); 
       }
    }

    public function store(AddSpendRequest $request)
    {
       try{
         $arrParam            = $request->all();
         $arrParam['user_id'] = 1; // auth()->user();
         $spend = $this->spendRepository->create($arrParam);
         
         return response()->json(['spend' => $spend]);
       }catch(Exception $e){
         return response()->json(['error' => $e->getMessage()], 500); 
       }
    }
    public function destroy($id)
    {
      try{
        $this->spendRepository->delete($id);
        return response()->json(['success' => true]);
      }catch(Exception $e){
        return response()->json(['error' => $e->getMessage()], 500); 
      }
    }

  // private function checkUser($user_id)
  // {
  //     $user = $this->userRepository->detail($user_id);
  //     if(empty($user_id)) return abort(404);
  //     return $user;
  // }
}

resources/views/admin/spends/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Thêm chi tiêu')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tài khoản</h4>
                    <p class="card-description mb-5">
                        Chi tiêu
                        <code>Thêm chi tiêu</code>
                    </p>
                    <form class="forms-sample" method="post" action="{{route('admin.spends.store', ['category_id' => $category->id,'user_id' => $category->user->id])}}" >
                        @csrf
                        <div class="form-group">
                            <label for="type">Chọn kiểu: &nbsp;</label>
                            <label>Thu nhập
                                <input type="radio" checked name="type" value="{{\App\Model\Spend::RECEIVE}}">
                            </label>
                            <label>Chi tiêu
                                <input type="radio" name="type" value="{{\App\Model\Spend::BUY}}">
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="type">Danh mục</label>
                            <select class="form-control" name="category_id">
                                <option selected value="{{ $category->id }}">{{ $category->name }}</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="total">Tổng tiền: </label>
                            <input type="text" class="form-control"  value="{{old('total')}}" name="total" placeholder="Nhập số tiền !">
                        </div>
                        <div class="form-group">
                            <label for="created_at">Ngày: </label>
                            <input type="text" class="form-control"  id="datepicker" value="{{old('created_at')}}" name="created_at" placeholder="Chọn ngày !">
                        </div>
                        <button type="submit" class="btn btn-success mr-2">Lưu</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="text/javascript">
        $( function() {
            $( "#datepicker" ).datepicker();
        } );
    </script>
@endsection

resources/views/admin/spends/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Chỉnh sửa chi tiêu')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tài khoản</h4>
                    <p class="card-description mb-5">
                        Chi tiêu
                        <code>Thêm chi tiêu</code>
                    </p>
                    <form class="forms-sample" method="post" action="{{route('admin.spends.update', ['category_id' => $category_id,'spend_id'=> $spend->id])}}" >
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="type">Chọn kiểu: &nbsp;</label>
                            <label>Thu nhập
                                <input type="radio" {{ ($spend->type == \App\Model\Spend::RECEIVE ) ? "checked" : '' }} name="type" value="{{\App\Model\Spend::RECEIVE}}">
                            </label>
                            <label>Chi tiêu
                                <input type="radio" {{ ($spend->type == \App\Model\Spend::BUY ) ? "checked" : '' }} name="type" value="{{\App\Model\Spend::BUY}}">
                            </label>
                        </div>
                        <div class="form-group">
                            <label for="total">Tổng tiền: </label>
                            <input type="text" class="form-control"  value="{{$spend->total}}" name="total" placeholder="Nhập số tiền !">
                        </div>
                        <div class="form-group">
                            <label for="created_at">Ngày: </label>
                            <input type="text" class="form-control"  id="datepicker" value="{{ $spend->created_at }}" name="created_at" placeholder="Chọn ngày !">
                        </div>
                        <button type="submit" class="btn btn-success mr-2">Lưu</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="text/javascript">
        $( function() {
            $( "#datepicker" ).datepicker();
        } );
    </script>
@endsection

resources/views/admin/spends/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Chi tiêu')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Quản lý chi tiêu</h4>
                    <p class="card-description mb-5">
                        <span>Danh mục</span>
                        <code>{{$category->name}}</code>
                        <a href="{{route('admin.spends.create', ['category_id' => $category->id])}}" class="btn btn-secondary float-right">Thêm chi tiêu</a>
                    </p>
                    <div class="table-responsive">
                        <table class="table table-bordered text-center">
                            <thead>
                            <tr>
                                <th>
                                    STT
                                </th>
                                <th>Type</th>
                                <th>Ngày tạo</th>
                                <th>Tổng tiền</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $stt =1;?>
                            @forelse($spends as $spend)
                                <tr>
                                    <td>{{ $stt }}</td>
                                    <td>
                                        <a href="{{ route('admin.spends.statistic.type',['category_id' => $category->id]).'?type='.$spend->type }}">
                                            {{ $spend->type_format }}
                                        </a>
                                    </td>
                                    <td>
                                        {{$spend->created_at_format}}
                                    </td>
                                    <td>
                                        <code>{{$spend->total_format}}</code>
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.spends.edit',['category_id' => $category->id,'spend_id' => $spend->id]) }}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                    </td>
                                    <td>
                                        <form action="{{ route('admin.spends.delete',['category_id' =>$category->id,'spend_id' => $spend->id]) }}" class="form-edit formConfirmDeleteSpend" method="post">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <input type="submit" class="btn btn-danger submitDelete" value="Xóa">
                                        </form>
                                    </td>
                                </tr>
                                <?php $stt++;?>
                            @empty
                                <tr>
                                    <td colspan="12" class="text-center">@lang('messages.no_data')</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('script')
    <script type="text/javascript">
        $('form.formConfirmDeleteSpend .submitDelete').click(function () {
            $('form.formConfirmDeleteCat').submit();
        })
    </script>
    @endsection

resources/views/admin/spends/statistic.blade.php
@extends('admin.layouts.app')

@section('title', 'Chi tiêu')
@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Quản lý chi tiêu</h4>
                    <p class="card-description mb-5">
                        <span>Thống kê</span>
                        <code>Chi tiêu</code>
                    </p>
                    <div class="statistic">
                        <div class="filters border border-primary" style="padding: 15px; margin-bottom: 20px;">
                            <button class="btn btn-success rounded">Lọc dữ liệu</button>

                            <a class="btn btn-info btn-xs" href="{{route('admin.spends.filter',['user_id' => $user_id]).'?filter=yesterday'}}">Hôm qua</a>
                            <a class="btn btn-info btn-xs" href="{{route('admin.spends.filter',['user_id' => $user_id]).'?filter=today'}}">Hôm nay</a>

                            <a class="btn btn-info btn-xs" href="{{route('admin.spends.filter',['user_id' => $user_id]).'?filter=week'}}">Tuần này</a>

                            <a class="btn btn-info btn-xs" href="{{route('admin.spends.filter',['user_id' => $user_id]).'?filter=month'}}">Tháng này</a>

                            <a class="btn btn-info btn-xs" href="{{route('admin.spends.filter',['user_id' => $user_id]).'?filter=receive'}}">Thu nhập</a>
                            <a class="btn btn-info btn-xs" href="{{route('admin.spends.filter',['user_id' => $user_id]).'?filter=buy'}}">Chi tiêu</a>

                            <a class="btn btn-info btn-xs" href="javascript:void(0)"  data-toggle="modal" data-target="#modalFilterDay">Chọn ngày</a>
                            <a class="btn btn-info btn-xs" href="{{route('admin.spends.filter',['user_id' => $user_id]).'?filter=clear'}}"><b>Không lọc</b></a>
                        </div>
                        <div class="filter_category_for_spends">
                            <form action="{{ route('admin.spends.filter',['user_id'=> $user_id]).'?filter=category' }}" method="POST" id="category">
                                {{ csrf_field() }}
                                {{ method_field('POST') }}
                                <div class="form-group">
                                    <label for="statistic">Thống kê chi tiêu:</label>
                                    <select name="filter_category" class="form-control" id="filter_category">
                                        <option value="0">@lang('messages.categories.option')</option>
                                        @forelse($categories as $category)
                                            <option value="{{ $category->id }}">{{ $category->name}}</option>
                                        @empty
                                            <option>@lang('messages.categories.no_data')</option>
                                        @endforelse
                                    </select>
                                </div>
                            </form>
                        </div>
                        <div class="table-responsive">
                            <table class="table table-bordered text-center">
                                <thead>
                                <tr>
                                    <th>Stt</th>
                                    <th>Ngày</th>
                                    <th>Danh mục</th>
                                    <th>Tổng tiền</th>
                                </tr>
                                </thead>
                                <tbody>
                                <?php $stt = 1; $buy = 0; $receive = 0;?>
                                @forelse($spends as $spend)
                                    @if($spend->type === \App\Model\Spend::BUY) <?php $buy += $spend->total  ?>
                                        @else <?php $receive += $spend->total  ?>
                                    @endif
                                <tr>
                                    <td>{{$stt}}</td>
                                    <td>{{ $spend->created_at_format }}</td>
                                    <td>{{ $spend->categories->name }}</td>
                                    <td class="{{(\App\Model\Spend::RECEIVE === $spend->type) ? 'text-success' : 'text-danger'}}">{{$spend->total_format}}</td>
                                </tr>
                                    <?php $stt++; ?>
                                @empty
                                    @lang('messages.no_data')
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                        <div class="cost" style="margin-top: 50px;">
                            <table class="table table-bordered text-center">
                                <thead>
                                <tr>
                                    <th class="bg-success rounded-top">TỔNG THU NHẬP</th>
                                    <th class="bg-danger rounded-top">TỔNG CHI TIÊU</th>
                                    <th class="bg-warning rounded-top">SỐ DƯ</th>
                                </tr>
                                </thead>
                                <tbody>

                                <tr>
                                    <td class="text-success">{{ number_format($receive)}} vnđ</td>
                                    <td class="text-danger">-{{number_format($buy)}} vnđ</td>
                                    <td class="text-warning">{{number_format($receive - $buy)}} vnđ</td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal -->
    <div class="modal fade" id="modalFilterDay" tabindex="-1" role="dialog"  aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalFilterDay">Lọc dữ liệu theo ngày</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form action="{{route('admin.spends.filter',['user_id' => $user_id]).'?filter=date'}}" method="post">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="created_at">Từ ngày: </label>
                            <input type="text" class="form-control datepicker" required   value="{{old('from_date')}}" name="from_date" >
                        </div>
                        <div class="form-group">
                            <label for="created_at">Dến ngày: </label>
                            <input type="text" class="form-control datepicker" required  value="{{old('to_date')}}" name="to_date">
                        </div>

                        <div ass="row">
                            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                            <button type="submit" class="btn btn-success">Đồng ý</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection
@section('script')
    <script type="text/javascript">
        $('#filter_category').change(function () {
            $('form#category').submit();
        })
        $( function() {
            $( ".datepicker" ).datepicker({dateFormat: "yy-mm-dd"});
        } );
    </script>
    @endsection