routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//// BUILD API
Route::get('/api/{path}', function(){
   return view('layouts/app');
})->where('path','.*');



Route::group(['namespace' => 'Auth'], function () {
    Route::get('logout', 'LogoutController@logout')->name('auth.logout');
    Route::get('active/{token}', 'ActiveUserController@active')->name('auth.active');
    
    Route::get('auth/facebook', 'FacebookController@redirectToFacebook');
    Route::get('auth/facebook/callback', 'FacebookController@handleFacebookCallback');
});
Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::middleware(['auth', 'admin'])->group(function () {
            Route::name('admin.')->group(function () {
                Route::get('/', 'AdminController@index')->name('index');
                Route::prefix('users')->group(function () {
                    Route::name('users.')->group(function () {
                        Route::get('/', 'UserController@index')->name('index');
                        Route::get('/create', 'UserController@create')->name('create');
                        Route::post('/create', 'UserController@store')->name('store');
                        Route::get('/edit/{id}', 'UserController@edit')->name('edit');
                        Route::put('/edit/{id}', 'UserController@update')->name('update');
                        Route::get('/edit-password/{id}', 'UserController@editPassword')->name('edit.password');
                        Route::put('/edit-password/{id}', 'UserController@updatePassword')->name('update.password');
                        Route::delete('/delete/{id}', 'UserController@delete')->name('delete');
                    });
                    Route::prefix('{user_id}')->group(function () {
                        Route::prefix('categories')->group(function () {
                            Route::name('categories.')->group(function () {
                                Route::get('/', 'CategoryController@index')->name('index');
                                Route::get('/create', 'CategoryController@create')->name('create');
                                Route::post('/create', 'CategoryController@store')->name('store');
                                Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
                                Route::put('/edit/{id}', 'CategoryController@update')->name('update');
                                Route::delete('/delete/{id}', 'CategoryController@delete')->name('delete');
                            });
                        });
                    });
                    Route::prefix('categories/{category_id}')->group(function () {
                        Route::prefix('spends')->group(function (){
                            Route::name('spends.')->group(function (){
                                Route::get('/','SpendController@index')->name('index');
                                Route::get('create','SpendController@create')->name('create');
                                Route::post('create/{user_id}','SpendController@store')->name('store');
                                Route::get('edit/{id}','SpendController@edit')->name('edit');
                                Route::put('edit/{id}','SpendController@update')->name('update');
                                Route::delete('/delete/{id}', 'SpendController@delete')->name('delete');
                                Route::get('statistic-type','SpendController@statisticType')->name('statistic.type');
                            });
                        });
                    });
                });
                Route::prefix('users/{user_id}')->group(function (){
                    Route::prefix('spends')->group(function (){
                        Route::name('spends.')->group(function (){
                            Route::get('/','SpendController@statistic')->name('statistic');
                            Route::match(['get', 'post'],'filter','SpendController@filterStatistic')->name('filter');
                        });
                    });
                });

            });
        });
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Requests\Admin\AddUserRequest;
use App\Http\Requests\Admin\EditPasswordRequest;
use App\Http\Requests\Admin\EditUserRequest;
use App\Jobs\ActiveUserJob;
use App\Jobs\ChangePassword;
use App\Repository\ProfileRepository;
use App\Repository\UserRepository;
use App\Services\UserServices;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class UserController extends Controller
{
    protected $repository;
    protected $profileRepository;
    protected $services;

    public function __construct()
    {
        $this->repository = app(UserRepository::class);
        $this->profileRepository = app(ProfileRepository::class);

        $this->services = app(UserServices::class);
    }

    public function index()
    {
        try {
            $users = $this->repository->paginate(PAGINATION_PER_PAGE, ['profile', 'role']);
            return view('admin.users.index', ['users' => $users]);
        } catch (\Exception $exception) {
            Log::error('ERROR_LIST_USERS'.$exception->getMessage());
            return abort(500);
        }


    }

    public function create()
    {
        return view('admin.users.create');
    }

    public function store(AddUserRequest $request)
    {
        DB::beginTransaction();
        try {
            $params = $request->all();
            $params['token_active'] = generateToken();
            $params['password'] = bcrypt($params['password']);
            $user = $this->repository->create($params);

            ActiveUserJob::dispatch($user)->onQueue('mails');

            $params['user_id'] = $user->id;
            $params['image']   =  $this->services->uploadImage($request->file('image'));

            $this->profileRepository->create($params);
            DB::commit();
            return redirect()->route('admin.users.index')->with('alert-success', trans('messages.success_created'));


        } catch (\Exception $exception) {
            DB::rollBack();
            Log::error('==================ERROR_ADD_USERS=========================='.$exception->getMessage());
            return abort(500);
        }
    }

    public function edit($id)
    {
        $user = $this->repository->detail($id, ['profile']);

        if (empty($user)) {
            return abort(404);
        }

        return view('admin.users.edit', ['user' => $user]);
    }

    public function editPassword($id)
    {
        $user = $this->repository->detail($id, ['profile']);

        if (empty($user)) {
            return abort(404);
        }

        return view('admin.users.edit-password', ['user' => $user]);
    }

    public function updatePassword($id, EditPasswordRequest $request)
    {
        try {
            $user = $this->repository->detail($id);

            if (empty($user)) {
                return abort(404);
            }

            if (auth()->user()->email !== $user->email) {
                ChangePassword::dispatch($user, $request->input('new_password'))->onQueue('mails');
            }


            $this->repository->update($user->id,['password' => bcrypt($request->input('new_password'))]);
            return redirect()->back()->with('alert-success', trans('messages.updated_success'));

        } catch (\Exception $exception) {
            Log::error('==================ERROR_EDIT_PASSWORD_USERS=========================='.$exception->getMessage());
            return abort(500);
        }


    }

    public function update($id, EditUserRequest $request)
    {
      try{
          $user = $this->repository->detail($id, ['profile']);

          if (empty($user)) {
              return abort(404);
          }

          $params = $request->all();
          $params['email'] = $user->email;


      }catch (\Exception $e){
          Log::error('=========EDIT_USER========',$e->getMessage());
      }
    }

    public function delete($id)
    {
      try{
          $this->repository->delete($id);
          return redirect()->back()->with('alert-success', trans('messages.success_deleted'));
      }catch (\Exception $e){
         Log::error('===========ERROR_DELETE_USER===============', $e->getMessage());
         return abort(404);
      }
    }
}

resources/views/admin/users/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Thêm tài khoản mới')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tài khoản</h4>
                    <p class="card-description mb-5">
                        Tài khoản
                        <code>Thêm tài khoản</code>
                    </p>
                    <form class="forms-sample" method="post" action="{{route('admin.users.store')}}" enctype="multipart/form-data">
                        @csrf
                        <div class="form-group">
                            <label for="email">Địa chỉ email</label>
                            <input type="email" class="form-control" id="email" value="{{old('email')}}" name="email" placeholder="Nhập địa chỉ email">
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="first-name">Họ</label>
                                    <input type="text" class="form-control" id="first-name" value="{{old('first_name')}}" name="first_name" placeholder="Hãy nhập họ">
                                </div>
                                <div class="col-md-6">
                                    <label for="last-name">Tên</label>
                                    <input type="text" class="form-control" id="last-name" value="{{old('last_name')}}" name="last_name" placeholder="Hãy nhập tên">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="password">Nhập mật khẩu</label>
                            <input type="password" class="form-control" id="password" name="password" placeholder="Nhập mật khẩu">
                        </div>

                        <div class="form-group">
                            <label for="password-confirm">Nhập mật khẩu</label>
                            <input type="password" class="form-control" id="password-confirm" name="password_confirmation" placeholder="Nhập lại mật khẩu">
                        </div>
                        <div class="form-group">
                            <label for="role">Quyền truy cập</label>
                            <select class="form-control" id="role" name="role_id">
                                <option value="">Chọn quyền truy cập</option>
                                <option value="{{\App\Model\Role::ROLE_ADMIN}}" {{\App\Model\Role::ROLE_ADMIN == old('role_id') ? 'selected' : ''}}>@lang('messages.role.admin')</option>
                                <option value="{{\App\Model\Role::ROLE_MEMBER}}" {{\App\Model\Role::ROLE_MEMBER == old('role_id') ? 'selected' : ''}}>@lang('messages.role.member')</option>
                                <option value="{{\App\Model\Role::ROLE_CUSTOMER}}" {{\App\Model\Role::ROLE_CUSTOMER == old('role_id') ? 'selected' : ''}}>@lang('messages.role.customer')</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="role">Giới tính</label>
                            <select class="form-control" id="sex" name="sex">
                                <option value="{{\App\Model\Profile::SEX_UNKNOWN}}">Không khai báo</option>
                                <option value="{{\App\Model\Profile::SEX_MALE}}" {{\App\Model\Profile::SEX_MALE == old('sex') ? 'selected' : ''}}>Nam</option>
                                <option value="{{\App\Model\Profile::SEX_FEMALE }}" {{\App\Model\Profile::SEX_FEMALE == old('role_id') ? 'selected' : ''}}>Nữ</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="role">Hình ảnh</label>
                            <input type="file" class="form-control" name="image">
                        </div>
                        <button type="submit" class="btn btn-success mr-2">Gửi</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit-password.blade.php
@extends('admin.layouts.app')

@section('title', 'Sửa mật khẩu')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tài khoản</h4>
                    <p class="card-description mb-5">
                        Tài khoản
                        <code>Thông tin tài khoản</code>
                        <a href="{{route('admin.users.edit', $user->id)}}" class="btn btn-primary pull-right">Sửa tài khoản</a>
                    </p>
                    <form class="forms-sample" method="post" action="{{route('admin.users.update.password',['id' => $user->id])}}" enctype="multipart/form-data" id="edit_user">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="email">Địa chỉ email</label>
                            <input type="email" disabled class="form-control" id="email" value="{{$user->email}}" name="email" placeholder="Nhập địa chỉ email" >
                        </div>
                        <div class="form-group">
                            <label for="new_password">Nhập mật khẩu mới</label>
                            <input type="password" class="form-control" id="new_password"  name="new_password" placeholder="Nhập mật khẩu mới" >
                        </div>
                        <div class="form-group">
                            <label for="confirm_password">Nhập lại mật khẩu</label>
                            <input type="password" class="form-control" id="confirm_password" name="new_password_confirmation" placeholder="Nhập lại mật khẩu mới" >
                        </div>

                        <div class="form-group">
                            <label for="role">Hình ảnh</label>
                            <img src="{{asset('storage/users/avatar/'.(isset($user->profile->image) ? $user->profile->image : ''))}}" alt="{{isset($user->profile->last_name) ? $user->profile->last_name : ''}}" class="img img-responsive img-avatar" style="max-width: 300px;margin-bottom: 20px;">
                        </div>
                        <button type="submit" class="btn btn-success mr-2" >Chỉnh sửa</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Thông tin tài khoản')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tài khoản</h4>
                    <p class="card-description mb-5">
                        Tài khoản
                        <code>Thông tin tài khoản</code>
                        <a href="{{route('admin.users.edit.password', $user->id)}}" class="btn btn-primary pull-right">Sửa mật khẩu</a>
                    </p>
                    <form class="forms-sample" method="post" action="{{route('admin.users.update',['id' => $user->id])}}" enctype="multipart/form-data" id="edit_user">
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="email">Địa chỉ email</label>
                            <input type="email" disabled class="form-control" id="email" value="{{$user->email}}" name="email" placeholder="Nhập địa chỉ email" >
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-md-6">
                                    <label for="first-name">Họ</label>
                                    <input type="text" class="form-control" id="first-name" value="{{isset($user->profile->first_name) ? $user->profile->first_name : ''}}" name="first_name" placeholder="Hãy nhập họ" >
                                </div>
                                <div class="col-md-6">
                                    <label for="last-name">Tên</label>
                                    <input type="text" class="form-control" id="last-name" value="{{isset($user->profile->last_name) ? $user->profile->last_name : ''}}" name="last_name" placeholder="Hãy nhập tên" >
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="role">Quyền truy cập</label>
                            <select class="form-control" id="role" name="role_id" >
                                <option value="">Chọn quyền truy cập</option>
                                <option value="{{\App\Model\Role::ROLE_ADMIN}}" {{\App\Model\Role::ROLE_ADMIN == $user->role_id ? 'selected' : ''}}>@lang('messages.role.admin')</option>
                                <option value="{{\App\Model\Role::ROLE_MEMBER}}" {{\App\Model\Role::ROLE_MEMBER == $user->role_id ? 'selected' : ''}}>@lang('messages.role.member')</option>
                                <option value="{{\App\Model\Role::ROLE_CUSTOMER}}" {{\App\Model\Role::ROLE_CUSTOMER == $user->role_id ? 'selected' : ''}}>@lang('messages.role.customer')</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="role">Giới tính</label>
                            <select class="form-control" id="sex" name="sex" >
                                <option value="{{\App\Model\Profile::SEX_MALE}}" {{isset($user->profile->sex) && \App\Model\Profile::SEX_MALE == $user->profile->sex ? 'selected' : ''}}>Nam</option>
                                <option value="{{\App\Model\Profile::SEX_FEMALE }}" {{isset($user->profile->sex) && \App\Model\Profile::SEX_FEMALE == $user->role_id ? 'selected' : ''}}>Nữ</option>
                                <option value="{{\App\Model\Profile::SEX_UNKNOWN}}" {{isset($user->profile->sex) && $user->sex == \App\Model\Profile::SEX_UNKNOWN ? 'selected' : ''}}>Không khai báo</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="role">Hình ảnh</label>
                            <img src="{{asset('storage/users/avatar/'.(isset($user->profile->image) ? $user->profile->image : ''))}}" alt="{{isset($user->profile->last_name) ? $user->profile->last_name : ''}}" class="img img-responsive img-avatar" style="max-width: 300px;margin-bottom: 20px;">
                            <input type="file" class="form-control" name="image" >
                        </div>
                        <button type="submit" class="btn btn-success mr-2" >Chỉnh sửa</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/users/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Tài khoản')

{{--@section('sidebar')--}}
{{--@parent--}}

{{--<p>This is appended to the master sidebar.</p>--}}
{{--@endsection--}}

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tài khoản</h4>
                    <p class="card-description mb-5">
                        Danh sách
                        <code>Tài khoản</code>
                        <a href="{{route('admin.users.create')}}" class="btn btn-secondary float-right">Thêm tài khoản</a>
                    </p>
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead>
                            <tr>
                                <th>
                                    ID
                                </th>
                                <th>
                                    Họ tên
                                </th>
                                <th>
                                    Giới tính
                                </th>
                                <th>
                                    Quyền
                                </th>
                                <th>
                                    Trạng thái
                                </th>
                                <th>Ngày tạo</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($users as $user)
                            <tr>
                                <td><a href="{{route('admin.users.edit', $user->id)}}">{{$user->id}}</a></td>
                                <td>
                                    <a href="{{route('admin.users.edit', $user->id)}}">
                                    {{isset($user->profile->full_name) ? $user->profile->full_name : USER_EMPTY_PROFILE}}
                                    </a>
                                </td>
                                <td>
                                    {{isset($user->profile->sex_format) ? $user->profile->sex_format : USER_EMPTY_PROFILE}}
                                </td>
                                <td>
                                    {{$user->role->name}}
                                </td>
                                <td>
                                    {{$user->status_format}}
                                </td>
                                <td>
                                    {{$user->created_at}}
                                </td>
                                <td>
                                    <a href="{{ Route('admin.categories.index',['user_id' => $user->id]) }}"  data-toggle="tooltip" title="Xem danh mục !" class="btn btn-info"><i class="fas fa-indent"></i></a>
                                </td>
                                <td>
                                    <a href="{{ Route('admin.spends.statistic',['user_id' => $user->id]) }}" class="btn btn-primary" data-toggle="tooltip" title="Xem chi tiêu !"><i class="fas fa-hand-holding-usd"></i></a>
                                </td>
                            </tr>
                            @empty
                                <tr>
                                    <td colspan="12" class="text-center">@lang('messages.no_data')</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection