routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//// BUILD API
Route::get('/api/{path}', function(){
   return view('layouts/app');
})->where('path','.*');



Route::group(['namespace' => 'Auth'], function () {
    Route::get('logout', 'LogoutController@logout')->name('auth.logout');
    Route::get('active/{token}', 'ActiveUserController@active')->name('auth.active');
    
    Route::get('auth/facebook', 'FacebookController@redirectToFacebook');
    Route::get('auth/facebook/callback', 'FacebookController@handleFacebookCallback');
});
Route::namespace('Admin')->group(function () {
    Route::prefix('admin')->group(function () {
        Route::middleware(['auth', 'admin'])->group(function () {
            Route::name('admin.')->group(function () {
                Route::get('/', 'AdminController@index')->name('index');
                Route::prefix('users')->group(function () {
                    Route::name('users.')->group(function () {
                        Route::get('/', 'UserController@index')->name('index');
                        Route::get('/create', 'UserController@create')->name('create');
                        Route::post('/create', 'UserController@store')->name('store');
                        Route::get('/edit/{id}', 'UserController@edit')->name('edit');
                        Route::put('/edit/{id}', 'UserController@update')->name('update');
                        Route::get('/edit-password/{id}', 'UserController@editPassword')->name('edit.password');
                        Route::put('/edit-password/{id}', 'UserController@updatePassword')->name('update.password');
                        Route::delete('/delete/{id}', 'UserController@delete')->name('delete');
                    });
                    Route::prefix('{user_id}')->group(function () {
                        Route::prefix('categories')->group(function () {
                            Route::name('categories.')->group(function () {
                                Route::get('/', 'CategoryController@index')->name('index');
                                Route::get('/create', 'CategoryController@create')->name('create');
                                Route::post('/create', 'CategoryController@store')->name('store');
                                Route::get('/edit/{id}', 'CategoryController@edit')->name('edit');
                                Route::put('/edit/{id}', 'CategoryController@update')->name('update');
                                Route::delete('/delete/{id}', 'CategoryController@delete')->name('delete');
                            });
                        });
                    });
                    Route::prefix('categories/{category_id}')->group(function () {
                        Route::prefix('spends')->group(function (){
                            Route::name('spends.')->group(function (){
                                Route::get('/','SpendController@index')->name('index');
                                Route::get('create','SpendController@create')->name('create');
                                Route::post('create/{user_id}','SpendController@store')->name('store');
                                Route::get('edit/{id}','SpendController@edit')->name('edit');
                                Route::put('edit/{id}','SpendController@update')->name('update');
                                Route::delete('/delete/{id}', 'SpendController@delete')->name('delete');
                                Route::get('statistic-type','SpendController@statisticType')->name('statistic.type');
                            });
                        });
                    });
                });
                Route::prefix('users/{user_id}')->group(function (){
                    Route::prefix('spends')->group(function (){
                        Route::name('spends.')->group(function (){
                            Route::get('/','SpendController@statistic')->name('statistic');
                            Route::match(['get', 'post'],'filter','SpendController@filterStatistic')->name('filter');
                        });
                    });
                });

            });
        });
    });
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

app/Http/Controllers/Admin/CategoryController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Model\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use App\Repository\CategoryRepository;
use App\Http\Requests\Admin\AddCategoryRequest;
use App\Http\Requests\Admin\EditCategoryRequest;
use App\Repository\UserRepository;

class CategoryController extends Controller
{
    protected $categoryRepository;
    protected $userRepository;
    public function __construct()
    {
        $this->categoryRepository = app(CategoryRepository::class);
        $this->userRepository     = app(UserRepository::class);
    }

    public function index($user_id)
    {
        $this->checkUser($user_id);
        $categories = $this->categoryRepository->getCategoryFromUser($user_id);

        return view('admin.categories.index',['categories' => $categories,'user_id'=> $user_id]);

    }
    public function edit($user_id, $category_id)
    {
        $this->checkUser($user_id);
        $category = $this->categoryRepository->detail($category_id);
        if(empty($category)) return abort(404);
        return view('admin.categories.edit',['category' => $category,'user_id'=>$user_id]);
    }
    public function update($user_id, $id, EditCategoryRequest $request)
    {
      try{
          $this->checkUser($user_id);
          $this->categoryRepository->update($id,$request->all());
          return redirect()->route('admin.categories.index',['user_id'=>$user_id])->with('alert-success', trans('messages.success_updated'));
      }catch (\Exception $e){
          Log::error('==================ERROR_UPDATE_CATEGORIES=========================='.$e->getMessage());
          return abort(500);
      }
    }

    public function create($user_id)
    {
        $this->checkUser($user_id);
        return view('admin.categories.create',['user_id'=> $user_id]);
    }
    public function store($user_id,AddCategoryRequest $request)
    {
        try{
            $this->checkUser($user_id);
            $params = $request->all();
            $params['user_id'] = $user_id;
            $this->categoryRepository->create($params);
            return redirect()->route('admin.categories.index',['user_id' => $user_id])->with('alert-success', trans('messages.success_created'));

        }catch(\Exception $e){
            Log::error('==================ERROR_ADD_CATEGORIES=========================='.$e->getMessage());
            return abort(500);
        }

    }
    public function delete($id)
    {
        try{
            $this->categoryRepository->delete($id);
            return redirect()->back()->with('alert-success', trans('messages.success_deleted'));
        }catch(\Exception $e){
            Log::error('==================ERROR_DELETE_CATEGORIES=========================='.$e->getMessage());
            return abort(500);
        }
    }
    private function checkUser($user_id)
    {
        $user = $this->userRepository->detail($user_id);
        if(empty($user)){
            return abort(404);
        }
        return $user;
    }

}

app/Http/Controllers/Api/CategoryController.php
<?php

namespace App\Http\Controllers\Api;
use App\Http\Controllers\Controller;
use Illuminate\Http\Response;
use App\Repository\SpendRepository;
use App\Repository\CategoryRepository;
use Mockery\CountValidator\Exception;
use App\Http\Requests\User\AddCategoryRequest;
use App\Http\Requests\User\EditCategoryRequest;
use Illuminate\Support\Facades\Auth;
use App\Http\Controllers\Api\ApiController;

class CategoryController extends ApiController
{

  protected $categoryRepository;
  public function __construct()
  {
    parent::__construct();
    $this->categoryRepository = app(CategoryRepository::class);
  }
  public function index()
  {
    // checkUser;
    try {
      return $this->categoryRepository->getCategoryFromUser(1); // Auth::id()
     } catch (Exception $e) {
         return response()->json(['error' => $e->getMessage()], 500);
     }
  }  

  public function store(AddCategoryRequest $request)
  {
    // checkUser;
    try {
      $arrParam = $request->all();
      $arrParam['user_id'] = 1;
      $category = $this->categoryRepository->create($arrParam); // Auth::id()
      return $this->buildResponse(true, $category);

     } catch (Exception $e) {
         return response()->json(['error' => $e->getMessage()], 500);
     }
  }

  public function destroy($id)
  {
    try{
      $this->categoryRepository->delete($id);
      return response()->json(['success' => true]);
    }catch(Exception $e){
      return response()->json(['error' => $e->getMessage()], 500); 
    }
  }

  public function edit($id)
  {
    try{
      $category =  $this->categoryRepository->detail($id);
      return response()->json(['category' => $category]);
    }catch(Exception $e){
      return response()->json(['error' => $e->getMessage()], 500); 
    }
  }
  public function update(EditCategoryRequest $request, $id)
  {
    try{
      $category =  $this->categoryRepository->update($id, $request->all());
      return response()->json(['success' => true]);
    }catch(Exception $e){
      return response()->json(['error' => $e->getMessage()], 500); 
    }
  }
 
  // private function checkUser($user_id)
  // {
  //     $user = $this->userRepository->detail($user_id);
  //     if(empty($user_id)) return abort(404);
  //     return $user;
  // }
}

resources/views/admin/categories/create.blade.php
@extends('admin.layouts.app')

@section('title', 'Thêm thể loại mới')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Tài khoản</h4>
                    <p class="card-description mb-5">
                        Thể loại
                        <code>Thêm thể loại </code>
                    </p>
                    <form class="forms-sample" method="post" action="{{route('admin.categories.store', ['user_id' => $user_id])}}" >
                        @csrf
                        <div class="form-group">
                            <input type="text" class="form-control" id="name" value="{{old('name')}}" name="name" placeholder="Nhập danh mục !">
                        </div>
                        <button type="submit" class="btn btn-success mr-2">Gửi</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/edit.blade.php
@extends('admin.layouts.app')

@section('title', 'Thể loại')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Danh mục</h4>
                    <p class="card-description mb-5">
                        chỉnh sửa
                        <code>{{ $category->name }}</code>
                    </p>
                    <form class="forms-sample" method="post" action="{{route('admin.categories.update',['id' => $category->id,'user_id'=> $user_id])}}" >
                        @csrf
                        @method('PUT')
                        <div class="form-group">
                            <label for="name">Tên</label>
                            <input type="text" class="form-control" id="name" value="{{$category->name}}" name="name" placeholder="Nhập danh mục !">
                        </div>

                        <button type="submit" class="btn btn-success mr-2" >Chỉnh sửa</button>
                    </form>

                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/admin/categories/index.blade.php
@extends('admin.layouts.app')

@section('title', 'Danh mục')

@section('content')
    <div class="row">
        <div class="col-lg-12 grid-margin stretch-card">
            <div class="card">
                <div class="card-body">
                    <h4 class="card-title">Danh mục</h4>
                    <p class="card-description mb-5">
                        Danh sách
                        <code>danh mục</code>
                        <a href="{{route('admin.categories.create',['user_id'=>$user_id])}}" class="btn btn-secondary float-right">Thêm danh mục</a>
                    </p>
                    <div class="table-responsive">
                        <table class="table table-bordered text-center">
                            <thead>
                            <tr>
                                <th>
                                    ID
                                </th>
                                <th>Tên</th>
                                <th>Ngày tạo</th>
                                <th></th>
                                <th></th>
                            </tr>
                            </thead>
                            <tbody>
                            <?php $stt =1;?>
                            @forelse($categories as $category)
                                <tr>
                                    <td>{{ $stt }}</td>
                                    <td>
                                        <a data-toggle="tooltip" title="Xem chi tiêu !"  href="{{route('admin.spends.index',['id' => $category->id])}}">
                                            {{ $category->name }}
                                        </a>
                                    </td>
                                    <td>
                                        {{$category->created_at_format}}
                                    </td>
                                    <td>
                                        <a href="{{ route('admin.categories.edit',['id' => $category->id,'user_id' => $user_id]) }}" class="btn btn-info"><i class="fas fa-edit"></i></a>
                                    </td>
                                    <td>
                                        <form action="{{route('admin.categories.delete',['user_id' => $user_id,'id'=>$category->id])}}" class="form-edit formConfirmDeleteCat" method="post">
                                            {{ method_field('DELETE') }}
                                            {{ csrf_field() }}
                                            <input type="submit" class="btn btn-danger submitDelete" data-toggle="modal" data-target="#myModalDelete" value="Xóa">
                                        </form>
                                    </td>
                                </tr>
                                <?php $stt++;?>
                            @empty
                                <tr>
                                    <td colspan="12" class="text-center">@lang('messages.no_data')</td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('script')
    <script type="text/javascript">
        $('form.formConfirmDeleteCat .submitDelete').click(function () {
            $('form.formConfirmDeleteCat').submit();
        })
    </script>
    @endsection